version: '3.7'
services:
#  backend:
#    restart: always
#    container_name: backend
#    build:
#      context: .
#      dockerfile: Dockerfile
#    env_file:
#      - .env
#    ports:
#      - ${BACKEND_PORT}:${BACKEND_PORT}
#    depends_on:
#      - db
#    entrypoint: uvicorn --host 0.0.0.0 --port ${BACKEND_PORT} src.main:app

  db:
    restart: always
    container_name: db
    image: postgres:14
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db:/var/lib/postgresql/data

    command: -p ${DB_PORT}



volumes:
  db:
    name: db_app


